---
# --------------------------- #
#   User Site Configuration   #
# --------------------------- #

url: http://guy.carpenter.id.au/gaugette
title: Gaugette
subtitle: Building gauges and gadgets with Arduinos, Raspberry Pis and Switec stepper motors.
author: GuyC
simple_search: http://google.com/search
description:
root: /gaugette
destination: public/gaugette
markdown: maruku
recent_posts: 20
subscribe_rss: /gaugette/atom.xml
disqus_short_name: gaugetteblog
disqus_show_comment_count: true
google_analytics_tracking_id: UA-28552776-1
fackebook_like: true
google_plus_one: true
